name: gad_app_team
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------------------------------------------
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  flutter_secure_storage: ^9.0.0

  # 상태 관리
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # UI / 유틸
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  flutter_localizations:
    sdk: flutter

  # 차트 / 캘린더
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9

  # 미디어
  audioplayers: ^6.4.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.1
  path: ^1.8.3
  rive: ^0.13.9

  # 지도 / 위치 / 지오펜스 / 정적 HTTP
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  http: ^1.4.0

  # 위치 권한 및 현재 위치 얻기
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # 지오펜스 감지
  geofence_service: ^6.0.0

  # 로컬 푸시 알림
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  # 권한 요청
  permission_handler: ^12.0.0+1

  # 기타 기존 패키지
  google_fonts: ^6.2.1

  # home_widget: ^0.7.0

  # 애니메이션
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
    - assets/image/activating event.png
    - assets/image/belief.png
    - assets/image/consequence.png
    - assets/image/question_icon.png
    - assets/image/nice.png
    - assets/image/alternative thoughts.png
    - assets/image/imagination.png
    - assets/image/scenario_1.png
    - assets/image/scenario_2.png
    - assets/image/scenario_3.png

    - assets/image/delete.png
    - assets/image/attack.png
    - assets/image/men.png

    - assets/image/character1.png
    - assets/image/character2.png
    - assets/image/character3.png
    - assets/image/character4.png
    - assets/image/character5.png
    - assets/image/character6.png
    - assets/image/character7.png
    - assets/image/character8.png
    - assets/image/character9.png
    - assets/image/character10.png
    - assets/image/character11.png
    - assets/image/character12.png
    - assets/image/character13.png
    - assets/image/character14.png
    - assets/image/character15.png
    - assets/image/character16.png
    - assets/image/character17.png
    - assets/image/character18.png
    - assets/image/character19.png
    - assets/image/character20.png

    # 1주차 part1
    - assets/education_data/week1_part1_1.json
    - assets/education_data/week1_part1_2.json
    - assets/education_data/week1_part1_3.json
    - assets/education_data/week1_part1_4.json
    - assets/education_data/week1_part1_5.json
    - assets/education_data/week1_part1_6.json

    # 1주차 part2
    - assets/education_data/week1_part2_1.json
    - assets/education_data/week1_part2_2.json
    - assets/education_data/week1_part2_3.json

    # 1주차 part3
    - assets/education_data/week1_part3_1.json
    - assets/education_data/week1_part3_2.json
    - assets/education_data/week1_part3_3.json
    - assets/education_data/week1_part3_4.json
    - assets/education_data/week1_part3_5.json
    - assets/education_data/week1_part3_6.json
    - assets/education_data/week1_part3_7.json
    - assets/education_data/week1_part3_8.json
    - assets/education_data/week1_part3_9.json

    # 1주차 part4
    - assets/education_data/week1_part4_1.json
    - assets/education_data/week1_part4_2.json
    - assets/education_data/week1_part4_3.json
    - assets/education_data/week1_part4_4.json
    - assets/education_data/week1_part4_5.json
    - assets/education_data/week1_part4_6.json

    # 1주차 part5
    - assets/education_data/week1_part5_1.json
    - assets/education_data/week1_part5_2.json
    - assets/education_data/week1_part5_3.json
    - assets/education_data/week1_part5_4.json
    - assets/education_data/week1_part5_5.json
    - assets/education_data/week1_part5_6.json
    - assets/education_data/week1_part5_7.json

    # 1주차 part6
    - assets/education_data/week1_part6_1.json
    - assets/education_data/week1_part6_2.json
    - assets/education_data/week1_part6_3.json
    - assets/education_data/week1_part6_4.json

    - assets/education_data/week1_relaxation_1.json
    - assets/education_data/week1_relaxation_2.json
    - assets/education_data/week1_relaxation_3.json
    - assets/education_data/week1_relaxation_4.json
    - assets/education_data/week1_relaxation_5.json

    - assets/relaxation/week1.riv
    - assets/relaxation/week1.mp3
    - assets/relaxation/week2.riv
    - assets/relaxation/week2.mp3
    - assets/relaxation/week3.riv
    - assets/relaxation/week3.mp3
    - assets/relaxation/week4.riv
    - assets/relaxation/week4.mp3
    - assets/relaxation/week7.riv
    - assets/relaxation/week7.mp3
    - assets/relaxation/week8.riv
    - assets/relaxation/week8.mp3

    - assets/image/alternative thoughts.png
    - assets/image/imagination.png

flutter_native_splash:
  color: "#F9F5F9"
  image: assets/image/logo.png
  android: true
  ios: true
  fullscreen: true