import 'dart:convert';
import 'dart:io';

void main() {
  final inputFile = File('dart_defines/kakao.api.json');
  final outputFile = File('ios/Flutter/Local.xcconfig');

  if (!inputFile.existsSync()) {
    stderr.writeln(
      'Missing ${inputFile.path}. Create it or run with --dart-define-from-file.',
    );
    exitCode = 1;
    return;
  }

  final decoded = jsonDecode(inputFile.readAsStringSync());
  if (decoded is! Map) {
    stderr.writeln('Expected a JSON object in ${inputFile.path}.');
    exitCode = 1;
    return;
  }

  final dartDefines = <String>[];
  for (final entry in decoded.entries) {
    final key = entry.key.toString().trim();
    final value = entry.value?.toString().trim() ?? '';
    if (key.isEmpty || value.isEmpty) continue;
    dartDefines.add(base64Encode(utf8.encode('$key=$value')));
  }

  if (dartDefines.isEmpty) {
    stderr.writeln('No non-empty dart defines found in ${inputFile.path}.');
    exitCode = 1;
    return;
  }

  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(
    [
      '// Local-only file generated by tool/sync_ios_local_xcconfig.dart.',
      '// Keeps iOS builds in Xcode/Flutter aligned with dart_defines/kakao.api.json.',
      'DART_DEFINES=\$(inherited),${dartDefines.join(',')}',
      '',
    ].join('\n'),
  );

  stdout.writeln(
    'Wrote ${outputFile.path} with ${dartDefines.length} local dart defines.',
  );
}
